# Tomcat配置
server:
    # 设置Tomcat的URI编码为UTF-8
    tomcat:
        uri-encoding: UTF-8
    # 设置Tomcat的端口号为8080
    port: 8080
    # 设置Servlet的上下文路径为/gerenjiankangguanlixitong
    servlet:
        context-path: /gerenjiankangguanlixitong

# Spring配置
spring:
    # 数据源配置
    datasource:
        # 数据库驱动类名
        driverClassName: com.mysql.jdbc.Driver
        # 数据库连接URL
        url: jdbc:mysql://127.0.0.1:3306/gerenjiankangguanlixitong?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=false
        # 数据库用户名
        username: root
        # 数据库密码
        password: 123456

    # Servlet配置
    servlet:
      # 多部分文件上传配置
      multipart:
        # 最大文件大小为1000MB
        max-file-size: 1000MB
        # 最大请求大小为1000MB
        max-request-size: 1000MB
    # 资源配置
    resources:
      # 静态资源位置，包括类路径和文件系统路径
      static-locations: classpath:static/,file:static/

# MyBatis配置
mybatis-plus:
  # Mapper XML文件位置
  mapper-locations: classpath*:mapper/*.xml
  # 实体类扫描包路径，多个包用逗号或分号分隔
  typeAliasesPackage: com.entity
  # 全局配置
  global-config:
    # 主键类型：0:"数据库ID自增", 1:"用户输入ID", 2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID"
    id-type: 1
    # 字段策略：0:"忽略判断", 1:"非 NULL 判断", 2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新Mapper，调试神器
    refresh-mapper: true
    # 逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    # 自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  # MyBatis配置
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 关闭缓存
    cache-enabled: false
    # 在设置null值时调用setter方法
    call-setters-on-nulls: true
    # 设置JdbcType为null，适用于Oracle数据库
    jdbc-type-for-null: 'null'

# 日志配置
logging:
  # 日志级别配置
  level:
    # 设置com.dao包的日志级别为debug
    com.dao: debug
